export enum ActorType {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  TEACHER = 'TEACHER',
  PARENT = 'PARENT',
  STAFF = 'STAFF',
}

export enum PlanCode {
  BASIC = 'BASIC',
  ADVANCE = 'ADVANCE',
  PREMIUM = 'PREMIUM',
  ENTERPRISE = 'ENTERPRISE',
}

export enum PermissionCode {
  // System & Subscription
  SUPER_ADMIN_ALL = 'SUPER_ADMIN_ALL',
  SUBSCRIPTION_OVERRIDE = 'SUBSCRIPTION_OVERRIDE',
  PLAN_MANAGE = 'PLAN_MANAGE',
  PLAN_VIEW = 'PLAN_VIEW',
  SCHOOL_MANAGE = 'SCHOOL_MANAGE',
  SUBSCRIPTION_VIEW = 'SUBSCRIPTION_VIEW',
  SUBSCRIPTION_MANAGE = 'SUBSCRIPTION_MANAGE',
  TOPUP_MANAGE = 'TOPUP_MANAGE',
  USAGE_VIEW = 'USAGE_VIEW',

  // Academic Setup
  ACADEMIC_SETUP_VIEW = 'ACADEMIC_SETUP_VIEW',
  ACADEMIC_SETUP_MANAGE = 'ACADEMIC_SETUP_MANAGE',

  // Onboarding & Directory
  STUDENT_CREATE = 'STUDENT_CREATE',
  STUDENT_VIEW = 'STUDENT_VIEW',
  TEACHER_CREATE = 'TEACHER_CREATE',
  TEACHER_VIEW = 'TEACHER_VIEW',

  // Fee Management
  FEE_INVOICE_VIEW = 'FEE_INVOICE_VIEW',
  FEE_STRUCTURE_VIEW = 'FEE_STRUCTURE_VIEW',
  FEE_STRUCTURE_MANAGE = 'FEE_STRUCTURE_MANAGE',
  FEE_PAYMENT_RECORD = 'FEE_PAYMENT_RECORD',
  FEE_WAIVER_APPLY = 'FEE_WAIVER_APPLY',
  FEE_REFUND_PROCESS = 'FEE_REFUND_PROCESS',

  // Communication
  BROADCAST_SEND = 'BROADCAST_SEND',
}
